Add bookings
UserNameToHub/java-shareit pull request #2
Opened 2023-07-30 18:01 UTC by UserNameToHub

2023-07-31 05:49 UTC, EugeneLenkevich requested changes
Привет, Александр, спасибо за PR

Видно что задание хорошо проработано с технической стороны, ожинг только join fetch чего стоит)
Однако вот что хочется отметить. 
1. Если уж делаешь что-то то делай единообразно. В частности, сортировка в запросах делается тремя способами (order by, sort, pageable). Лучше выбрать только один способ и использовать только его, так будет единообразно, предлагаю использовать Pageable как самый универсальный
2. Вооще, чем код проще, тем он понятней и тем его потом легче, читай дешевле, поддерживать, может можно обойтись меньшим количеством dto, как это можно упростить :)

2023-07-31 05:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "order by bk.startDate desc")
У нас в параметрах метода есть Pageable, в нем есть возможность указать сортировку, тут, в запросе, тогда лучше сортировку убрать иначе получается такой смысловой конфликт :)

2023-07-31 05:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/CommentGettingTo.java
> +public class CommentGettingTo {
Не совсем понятно именование объекта, дословно "коментарий попадающий в"
"To" - это направление,  может тут подразумевалось существительное Dto (data transfer object) ?

В идеале хотчется чтобы код читался как обычный текст. Тут же, из именования объекта не совсем понятно про что он, может просто оставить CommentDto?  :)

И далее идет целая пачка dto, а надо ли столько, нельзя ли обойтись меньшим количеством, в этом же всем потом надо будет разбираться, поддерживать, эта специализация dto точно оправдана, нет ли тут переусложнения, не плодим ли лишние сущности? :)

2023-08-02 13:13 UTC, UserNameToHub commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "order by bk.startDate desc")
Привет! Спасибо за коммент) 

Испаравил)

2023-08-02 13:14 UTC, UserNameToHub commented on src/main/java/ru/practicum/shareit/item/dto/CommentGettingTo.java
> +public class CommentGettingTo {
Еще раз спасибо!:)

Согласен, чет я Dtошек налепил) Постарался минисизировать)

2023-08-02 16:24 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-03 21:04 UTC, merged